function comparison_plot(numerical_IRF, analytical_lower, analytical_upper, collector, response, shock, VAR_config, FLAGcumsum, pic_config)
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % comparison_plot Function to produce Figures 9 and 10 in appendix B.
    %    Comparsion with Gafarov, Meier and Montiel Olea(2018)
    %
    % Inputs
    % numerical_IRF - IRF's computed using RRWZ (2010) algorithm
    % analytical_IRF - IRF's computed using Gafarov, Meier and Montiel
    %   Olea(2018)
    % collector - draw info from numerical IRF
    % reponse - variable number of response
    % shock - variable number of shock
    % VAR_config - object generated by SVAR_config.m
    % FLAGcumsum - logical flag for cumulative sum
    % pic_config - object generated by pic_config.m
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
    % for dedugging
    debug = 0;
    if debug == 1
        analytical_lower = ana_lower;
        analytical_upper = ana_upper;
        VAR_config = t1_VAR_config;
        pic_config = picture_config;
        numerical_IRF = t1_IRF;
        collector = t1_collector;
        FLAGcumsum = false;
        response = 1;
        shock = 1;
    end
 
    % Unspool
    drawMatrix = VAR_config.drawMatrix;
    nhorizon = VAR_config.nhorizon;
    names = VAR_config.names;
 
    fig_fontsize = pic_config.fontsize;
    fig_width = pic_config.width;
    fig_height = pic_config.height;
    pic_dir = pic_config.directory;
 
    figure('Name', 'Ana_Num')
    colormat = {'black', 'blue', 'red', 'green'}; % {Anal, num}
 
    % Figure 9
    for ii = 1:size(drawMatrix, 1)
        if FLAGcumsum == 0
         
            num_upper(:, :, :, ii) = permute(max(numerical_IRF(:, :, :, 1: 1:collector(ii, 1)), [], 4), [3 1 2]);
            num_lower(:, :, :, ii) = permute(min(numerical_IRF(:, :, :, 1: 1:collector(ii, 1)), [], 4), [3 1 2]);
         
            plot_analytical_upper = analytical_upper;
            plot_ana_lower = analytical_lower;
         
            % Cumsum
        elseif FLAGcumsum == 1
         
            num_upper(:, :, :, ii) = cumsum(permute(max(numerical_IRF(:, :, :, 1: 1:collector(ii, 1)), [], 4), [3 1 2]), 1);
            num_lower(:, :, :, ii) = cumsum(permute(min(numerical_IRF(:, :, :, 1: 1:collector(ii, 1)), [], 4), [3 1 2]), 1);
         
            plot_analytical_upper = cumsum(analytical_upper, 1);
            plot_ana_lower = cumsum(ana_lower, 1);
        end
     
        % Compute differences
        diff_upper(:, :, ii) = plot_analytical_upper(1:nhorizon, :) - num_upper(1:nhorizon, :, shock, ii);
        diff_lower(:, :, ii) = plot_ana_lower(1:nhorizon, :) - num_lower(1:nhorizon, :, shock, ii);
     
        % Analytical
        % Upper
        plot(0 : nhorizon - 1, plot_analytical_upper(1:nhorizon, response), ...
        'LineWidth', 1, 'Color', colormat{1});
        hold on;
        % Lower
        plot(0 : nhorizon - 1, plot_ana_lower(1:nhorizon, response), ...
        'LineWidth', 1, 'Color', colormat{1});
     
        % Legend
        leg(size(drawMatrix, 1) + 1) = plot(NaN, NaN, 'DisplayName', 'Analytical', 'LineWidth', 1, 'Color', colormat{1});
     
        % Numerical
        plot(0 : nhorizon - 1, num_upper(1:nhorizon, response, shock, ii), ...
        'LineWidth', 1, 'Color', colormat{ii + 1});
        plot(0 : nhorizon - 1, num_lower(1:nhorizon, response, shock, ii), ...
          'LineWidth', 1, 'Color', colormat{ii + 1});
     
        % Legend
        leg(ii) = plot(NaN, NaN, 'DisplayName', ['Draws = ' num2str(collector(ii, 1))], 'LineWidth', 1, 'Color', colormat{ii + 1});
        % Legend
    end
    leg2 = legend(leg);
    set(leg2, 'Interpreter', 'latex')
    ylabel(['Response of $' names{response} '$'], 'fontsize', 12, 'Interpreter', 'latex');
    xlabel('Horizon', 'fontsize', 12, 'Interpreter', 'latex');
 
    % Pretty pictures
    latex_fig(fig_fontsize, fig_width, fig_height);
    tightfig();
    print(gcf, '-depsc2', fullfile(pic_dir, ['Ana_num.eps']))
 
    % Figure 10
    figure('Name', 'Comparison')
 
    for ii = 1:size(drawMatrix, 1)
        plot(0 : nhorizon - 1, diff_upper(:, response, ii), ...
          'LineWidth', 1, 'Color', colormat{ii + 1});
        hold on;
     
        plot(0 : nhorizon - 1, diff_lower(:, response, ii), ...
          'LineWidth', 1, 'Color', colormat{ii + 1});
     
        diff_leg(ii) = plot(NaN, NaN, 'DisplayName', ['Draws = ' num2str(collector(ii, 1))], ...
          'LineWidth', 1, 'Color', colormat{ii + 1});
     
    end
 
    % Zero line
    %plot(0 : nhorizon - 1, zeros(nhorizon),  'LineWidth', 1, 'Color', 'black');
    diff_leg2 = legend(diff_leg);
    set(diff_leg2, 'Interpreter', 'latex')
    ylabel(['Response of $' names{response} '$'], 'fontsize', 12, 'Interpreter', 'latex');
    xlabel('Horizon', 'fontsize', 12, 'Interpreter', 'latex');
    latex_fig(fig_fontsize, fig_width, fig_height);
    tightfig();
 
    print(gcf, '-depsc2', fullfile(pic_dir, ['differences.eps']))
 
end


