function task2_plot(og_IRF, IRF, indexmatrix, collector, response, shock, VAR_config, FLAGcumsum, pic_config, point_id)
 
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % task2_plot Produce Figure 4
    %
    % Inputs
    % og_IRF - Point ID IRF (not shown in paper) as point_ID = 0
    % IRF
    % indexmatrix
    % collector - draw info from numerical IRF
    % reponse - variable number of response
    % shock - variable number of shock
    % VAR_config - object generated by SVAR_config.m
    % FLAGcumsum - logical flag for cumulative sum
    % pic_config - object generated by pic_config.m
    % point_ID - indictator of whether to include og_IRF
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 
    drawMatrix = VAR_config.drawMatrix;
    nhorizon = VAR_config.nhorizon;
    names = VAR_config.names;
 
    fig_fontsize = pic_config.fontsize;
    fig_width = pic_config.width;
    fig_height = pic_config.height;
    pic_dir = pic_config.directory;
 
    figure('Name', 'IK Shotgun')
 
    colormat = {'blue', 'red'}; % Shotguns
    ogcolor = 'green'; % Orginal IRF color
 
    if FLAGcumsum == 0
        plot_IRF = squeeze(IRF(response, shock, 1:nhorizon, :));
        plot_og_IRF = og_IRF;
    elseif FLAGcumsum == 1
        plot_IRF = cumsum(squeeze(IRF(ill_shotgun_res, ill_shotgun_shock, 1:nhorizon, :)));
        plot_og_IRF = cumsum(og_IRF);
    end
 
    for ii = size(collector, 1): - 1:1 % reverse order for better pictures
     
        % Shotgun plots
        plot(0:nhorizon - 1, plot_IRF(:, indexmatrix(1:collector(ii, 1), ii)), ...
        'LineWidth', 1, 'Color', colormat{ii});
        hold on;
     
        % Legend
        t2_leg(ii) = plot(NaN, NaN, 'DisplayName', ... %['Total = ' num2str(collector(ii, 2)) ...
          ['Draws = ' num2str(collector(ii, 1))], 'LineWidth', 1, 'Color', colormat{ii});
     
        % Black bands
        plot(0:nhorizon - 1, max(plot_IRF(:, indexmatrix(1:collector(ii, 1), ii)), [], 2), 'k-', ...
          0:nhorizon - 1, min(plot_IRF(:, indexmatrix(1:collector(ii, 1), ii)), [], 2), 'k-', 'linewidth', 2)
    end
 
    % Original IRF
    if point_id == 1
        plot(0:nhorizon - 1, squeeze(plot_og_IRF(response, shock, :)), 'LineWidth', 2, 'Color', 'green');
        t2_leg(size(collector, 1) + 1) = plot(NaN, NaN, 'DisplayName', 'Point-ID IRF', ...
          'LineWidth', 3, 'Color', ogcolor);
    end
 
    % Its legend
    t2_leg2 = legend(t2_leg);
    set(t2_leg2, 'Interpreter', 'latex')
 
    %title(['IK Shotgun plots'], 'fontsize', 12)
    ylabel(['Response of $' names{response} '$'], 'fontsize', 12, 'Interpreter', 'latex');
    xlabel('Horizon', 'fontsize', 12, 'Interpreter', 'latex');
 
    latex_fig(fig_fontsize, fig_width, fig_height);
    tightfig();
    if point_id == 1
        print(gcf, '-depsc2', fullfile(pic_dir, ['ik_shotgun_pointID.eps']))
    else
        print(gcf, '-depsc2', fullfile(pic_dir, ['ik_shotgun.eps']))
    end
end

